(()=>{
const $=s=>document.querySelector(s),state={ctx:null,range:'week',entries:[],breaks:[],employees:[],sites:[],corrections:[],loadId:0,dataReady:false,periodStart:null};const esc=v=>AONE.esc(v??'');
function startOfWeek(){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7));return d}function start(){const d=new Date();if(state.range==='today'){d.setHours(0,0,0,0);return d}if(state.range==='30'){d.setDate(d.getDate()-29);d.setHours(0,0,0,0);return d}return startOfWeek()}
function emp(id){return state.employees.find(x=>x.id===id)}function site(id){return state.sites.find(x=>x.id===id)}
function totals(entry){return AONE.entryHours(entry,state.breaks,{from:state.periodStart})}
function breakHours(entry){return totals(entry).breaks}
function worked(entry){return totals(entry).net}
function fmt(v){return new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}
function fillFilters(){const ev=$('#employee-filter').value,sv=$('#site-filter').value;$('#employee-filter').innerHTML='<option value="">Alle Mitarbeiter</option>'+state.employees.map(e=>`<option value="${e.id}">${esc(e.display_name)}</option>`).join('');$('#site-filter').innerHTML='<option value="">Alle Objekte</option>'+state.sites.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');$('#employee-filter').value=ev;$('#site-filter').value=sv}
function unavailable(text){['m-hours','m-open','m-corrections','m-employees'].forEach(id=>$('#'+id).textContent='—');$('#time-list').textContent=text;$('#correction-list').textContent=''}
async function load(){const loadId=++state.loadId;state.dataReady=false;unavailable('Arbeitszeiten werden geladen…');AONE.loading(true,'Arbeitszeiten werden geladen…');try{const org=state.ctx.org_id,from=start().toISOString();const [entries,employees,sites,corrections]=await Promise.all([AONE.tableAll('guard_time_entries',`select=*&org_id=eq.${encodeURIComponent(org)}&or=(clock_out_at.is.null,clock_out_at.gt.${encodeURIComponent(from)})&order=clock_in_at.desc`),AONE.table('guard_employees',`select=id,display_name,employee_no&org_id=eq.${encodeURIComponent(org)}&order=display_name.asc`),AONE.table('guard_sites',`select=id,name&org_id=eq.${encodeURIComponent(org)}&order=name.asc`),AONE.table('guard_time_corrections',`select=*&org_id=eq.${encodeURIComponent(org)}&status=eq.pending&order=requested_at.desc`)]);const breaks=await AONE.entryBreaks(entries||[]);if(loadId!==state.loadId)return;state.periodStart=new Date(from);state.dataReady=true;state.entries=entries||[];state.employees=employees||[];state.sites=sites||[];state.corrections=corrections||[];state.breaks=breaks;fillFilters();render()}catch(e){if(loadId!==state.loadId)return;state.dataReady=false;state.entries=[];state.breaks=[];state.corrections=[];['m-hours','m-open','m-corrections','m-employees'].forEach(id=>$('#'+id).textContent='—');$('#time-list').textContent='Arbeitszeiten konnten nicht vollständig geladen werden. Bitte erneut laden.';$('#correction-list').textContent='';AONE.toast(e.message,'err')}finally{if(loadId===state.loadId)AONE.loading(false)}}
function filtered(){const e=$('#employee-filter').value,s=$('#site-filter').value;return state.entries.filter(x=>(!e||x.employee_id===e)&&(!s||x.site_id===s))}
function render(){if(!state.dataReady)return;const list=filtered(),open=list.filter(x=>!x.clock_out_at),hours=list.reduce((n,x)=>n+worked(x),0);$('#m-hours').textContent=hours.toFixed(1).replace('.0','');$('#m-open').textContent=open.length;$('#m-corrections').textContent=state.corrections.length;$('#m-employees').textContent=new Set(list.map(x=>x.employee_id)).size;$('#range-label').textContent=`Nettozeit seit ${new Intl.DateTimeFormat('de-DE',{dateStyle:'medium'}).format(state.periodStart)}`;$('#time-list').innerHTML=list.length?list.map(x=>{const age=(Date.now()-new Date(x.clock_in_at))/3600000;return `<div class="time-row ${!x.clock_out_at&&age>12?'warn-row':''}"><div><b>${esc(emp(x.employee_id)?.display_name||'Mitarbeiter')}</b><div class="small">${esc(site(x.site_id)?.name||'Objekt')} · ${esc(x.clock_in_method||'app')}</div></div><div><div>${fmt(x.clock_in_at)}</div><div class="small">${x.clock_out_at?fmt(x.clock_out_at):'noch eingestempelt'}</div></div><div><b>${worked(x).toFixed(2)} h</b><div class="small">Pause ${breakHours(x).toFixed(2)} h</div></div><div>${x.clock_out_at?'<span class="ok-badge">Abgeschlossen</span>':'<span class="open-badge">Offen</span>'}</div><div class="small">${esc(x.status)}</div></div>`}).join(''):'<div class="empty">Keine Zeitbuchungen im gewählten Zeitraum.</div>';
 $('#correction-list').innerHTML=state.corrections.length?state.corrections.map(c=>`<article class="correction"><h4>${esc(emp(c.employee_id)?.display_name||'Mitarbeiter')}</h4><div class="small">Neu: ${fmt(c.requested_clock_in_at)} – ${fmt(c.requested_clock_out_at)}</div><p>${esc(c.reason)}</p><div class="actions"><button class="btn green small decide" data-id="${c.id}" data-decision="approved">Genehmigen</button><button class="btn red small decide" data-id="${c.id}" data-decision="rejected">Ablehnen</button></div></article>`).join(''):'<div class="empty">Keine offenen Korrekturanträge.</div>'}
async function decide(id,decision){const note=prompt(decision==='approved'?'Optionaler Hinweis zur Genehmigung:':'Optionaler Ablehnungsgrund:','')??'';AONE.loading(true,'Entscheidung speichern…');try{await AONE.rpc('guard_decide_time_correction',{p_request:id,p_decision:decision,p_note:note});await load();AONE.toast(decision==='approved'?'Korrektur genehmigt.':'Korrektur abgelehnt.')}catch(e){AONE.toast(e.message,'err')}finally{AONE.loading(false)}}
function setRange(r){state.range=r;document.querySelectorAll('.segmented button').forEach(b=>b.classList.remove('active'));$('#r-'+(r==='30'?'30':r)).classList.add('active');load()}
function bind(){$('#r-today').onclick=()=>setRange('today');$('#r-week').onclick=()=>setRange('week');$('#r-30').onclick=()=>setRange('30');$('#employee-filter').onchange=render;$('#site-filter').onchange=render;$('#refresh').onclick=load;$('#correction-list').onclick=e=>{if(e.target.classList.contains('decide'))decide(e.target.dataset.id,e.target.dataset.decision)};$('#logout').onclick=()=>{AONE.signOut();location.replace('./admin-login.html')}}
async function init(){const s=await AONE.session();if(!s){location.replace('./admin-login.html');return}const ctx=await AONE.chooseContext();if(!ctx||!AONE.isManager(ctx.role)){location.replace('./admin-login.html');return}state.ctx=ctx;$('#org-name').textContent=ctx.org?.name||'Arbeitszeiten';$('#who').textContent=AONE.roleLabel(ctx.role);bind();await load()}init().catch(e=>AONE.toast(e.message,'err'));
})();
