(()=>{
  const $=s=>document.querySelector(s); let session,ctx,employees=[],quals=[],leaves=[],docs=[],sites=[],requirements=[];
  const common=[['unterrichtung','Unterrichtung'],['sachkunde','Sachkunde'],['erste_hilfe','Erste Hilfe'],['brandschutz','Brandschutz'],['fuehrerschein','Führerschein'],['waffensachkunde','Waffensachkunde'],['objektunterweisung','Objektunterweisung']];
  const esc=AONE.esc;
  function modal(html){$('#modal').innerHTML=html;$('#modal-back').classList.add('open')}
  function close(){ $('#modal-back').classList.remove('open') }
  $('#modal-back').onclick=e=>{if(e.target.id==='modal-back')close()};
  function dateOnly(v){return v?String(v).slice(0,10):''}
  function daysTo(v){if(!v)return null;const a=new Date();a.setHours(0,0,0,0);const b=new Date(v+'T00:00:00');return Math.ceil((b-a)/86400000)}
  function qualStatus(q){if(!q)return {key:'missing',label:'Fehlt',cls:'red'};const d=daysTo(q.valid_until);if(d!==null&&d<0)return {key:'critical',label:'Abgelaufen',cls:'red'};if(d!==null&&d<=30)return {key:'warning',label:`${d} T.`,cls:'yellow'};if(!q.verified_at)return {key:'warning',label:'Ungeprüft',cls:'yellow'};return {key:'ok',label:'OK',cls:'green'}}
  function latestQual(emp,kind){return quals.filter(q=>q.employee_id===emp&&q.kind===kind).sort((a,b)=>String(b.valid_until||b.created_at).localeCompare(String(a.valid_until||a.created_at)))[0]||null}
  function employeeRisk(e){const reqKinds=new Set(requirements.filter(r=>r.active&&r.mandatory&&r.requirement_type==='qualification'&&!r.site_id).map(r=>r.requirement_key)); if(!reqKinds.size){reqKinds.add('unterrichtung');reqKinds.add('sachkunde')}
    let warning=false;for(const k of reqKinds){const s=qualStatus(latestQual(e.id,k));if(s.key==='critical'||s.key==='missing')return 'critical';if(s.key==='warning')warning=true}return warning?'warning':'ok'}
  async function guard(){session=await AONE.session().catch(()=>null);if(!session){location.replace('./admin-login.html');return false}ctx=await AONE.chooseContext();if(!ctx||!AONE.isManager(ctx.role)){location.replace('./app.html');return false}$('#org-name').textContent=ctx.org.name;$('#who').textContent=AONE.roleLabel(ctx.role);return true}
  async function load(){AONE.loading(true,'Compliance-Daten laden…');try{if(!await guard())return;const org=encodeURIComponent(ctx.org_id);[employees,quals,leaves,docs,sites,requirements]=await Promise.all([
      AONE.table('guard_employees',`select=id,display_name,employee_no,email,qualification_level,status,bewacher_id&org_id=eq.${org}&order=display_name.asc`),
      AONE.table('guard_qualifications',`select=*&org_id=eq.${org}&order=created_at.desc`),
      AONE.table('guard_leave_requests',`select=*&org_id=eq.${org}&order=created_at.desc`),
      AONE.table('guard_document_register',`select=id,employee_id,site_id,title,category,status,valid_until,document_no&org_id=eq.${org}&order=valid_until.asc.nullslast`),
      AONE.table('guard_sites',`select=id,name,customer_name,active&org_id=eq.${org}&order=name.asc`),
      AONE.table('guard_compliance_requirements',`select=*&org_id=eq.${org}&order=label.asc`)
    ]);renderAll()}catch(e){AONE.toast(e.message,'err')}finally{AONE.loading(false)}}
  function renderAll(){renderStats();renderFilters();renderMatrix();renderLeaves();renderExpiry();renderRequirements()}
  function renderStats(){const active=employees.filter(e=>e.status==='active');const risks=active.map(employeeRisk);const critical=risks.filter(x=>x==='critical').length;const warning=risks.filter(x=>x==='warning').length;const pending=leaves.filter(x=>x.status==='pending').length;const exp=docs.filter(d=>{const n=daysTo(d.valid_until);return n!==null&&n>=0&&n<=60}).length;$('#stats').innerHTML=`
    <div class="card metric-ok"><div class="kicker">Aktiv</div><div class="stat">${active.length}</div><div class="muted">Mitarbeiter</div></div>
    <div class="card metric-danger"><div class="kicker">Kritisch</div><div class="stat">${critical}</div><div class="muted">fehlend / abgelaufen</div></div>
    <div class="card metric-warn"><div class="kicker">Warnungen</div><div class="stat">${warning+exp}</div><div class="muted">Qualifikation / Dokument</div></div>
    <div class="card"><div class="kicker">Freigaben</div><div class="stat">${pending}</div><div class="muted">offene Abwesenheiten</div></div>`}
  function renderFilters(){const sel=$('#site-filter');const cur=sel.value;sel.innerHTML='<option value="">Alle Objekte</option>'+sites.filter(s=>s.active).map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');sel.value=cur}
  function matrixKinds(){const required=requirements.filter(r=>r.active&&r.requirement_type==='qualification'&&!r.site_id).map(r=>[r.requirement_key,r.label]);const map=new Map([...common,...required]);return [...map.entries()].slice(0,8)}
  function renderMatrix(){const kinds=matrixKinds();$('#matrix-head').innerHTML='<tr><th>Mitarbeiter</th>'+kinds.map(([,l])=>`<th>${esc(l)}</th>`).join('')+'<th>Status</th></tr>';const term=$('#search').value.trim().toLowerCase();const rf=$('#risk-filter').value;let rows=employees.filter(e=>e.status==='active'&&(!term||`${e.display_name} ${e.employee_no||''}`.toLowerCase().includes(term)));if(rf!=='all')rows=rows.filter(e=>employeeRisk(e)===rf);$('#matrix-body').innerHTML=rows.length?rows.map(e=>{const r=employeeRisk(e);return `<tr><td><b>${esc(e.display_name)}</b><div class="tiny muted">${esc(e.employee_no||'ohne Personalnr.')} · ${esc(e.qualification_level||'none')}</div>${['owner','admin'].includes(ctx.role)?`<a class="tiny" href="./personalakte.html?id=${encodeURIComponent(e.id)}">Personalakte öffnen</a>`:''}</td>${kinds.map(([k])=>{const q=latestQual(e.id,k),s=qualStatus(q);return `<td class="status-cell"><span class="pill ${s.cls}" title="${q?.valid_until?`gültig bis ${dateOnly(q.valid_until)}`:'kein Ablaufdatum'}">${s.label}</span></td>`}).join('')}<td><span class="pill ${r==='critical'?'red':r==='warning'?'yellow':'green'}">${r==='critical'?'Handlungsbedarf':r==='warning'?'Prüfen':'Vollständig'}</span></td></tr>`}).join(''):'<tr><td colspan="20" class="empty">Keine Mitarbeiter gefunden.</td></tr>'}
  function renderLeaves(){const pending=leaves.filter(x=>x.status==='pending');$('#leave-list').innerHTML=pending.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Mitarbeiter</th><th>Art</th><th>Zeitraum</th><th>Aktion</th></tr></thead><tbody>${pending.map(l=>{const e=employees.find(x=>x.id===l.employee_id);return `<tr><td>${esc(e?.display_name||'—')}</td><td>${l.kind==='vacation'?'Urlaub':l.kind==='sick'?'Krank':'Sonstiges'}</td><td>${AONE.d(l.starts_on)} – ${AONE.d(l.ends_on)}${l.note?`<div class="tiny muted">${esc(l.note)}</div>`:''}</td><td><div class="actions-inline"><button class="btn small green" data-leave="approved" data-id="${l.id}">Genehmigen</button><button class="btn small red" data-leave="rejected" data-id="${l.id}">Ablehnen</button></div></td></tr>`}).join('')}</tbody></table></div>`:'<div class="empty">Keine offenen Anträge.</div>';document.querySelectorAll('[data-leave]').forEach(b=>b.onclick=()=>decideLeave(b.dataset.id,b.dataset.leave))}
  async function decideLeave(id,status){try{await AONE.update('guard_leave_requests',`id=eq.${encodeURIComponent(id)}&org_id=eq.${encodeURIComponent(ctx.org_id)}`,{status,decided_by:session.user.id,decided_at:new Date().toISOString()});AONE.toast(status==='approved'?'Genehmigt.':'Abgelehnt.');await load()}catch(e){AONE.toast(e.message,'err')}}
  function renderExpiry(){const items=[];quals.forEach(q=>{const n=daysTo(q.valid_until);if(n!==null&&n<=60){items.push({type:'Qualifikation',title:q.kind,days:n,employee_id:q.employee_id})}});docs.forEach(d=>{const n=daysTo(d.valid_until);if(n!==null&&n<=60){items.push({type:'Dokument',title:d.title,days:n,employee_id:d.employee_id})}});items.sort((a,b)=>a.days-b.days);$('#expiry-list').innerHTML=items.length?`<div class="stack">${items.slice(0,15).map(x=>{const e=employees.find(y=>y.id===x.employee_id);return `<div class="row between"><div><b>${esc(x.title)}</b><div class="tiny muted">${esc(x.type)} · ${esc(e?.display_name||'ohne Mitarbeiter')}</div></div><span class="pill ${x.days<0?'red':x.days<=30?'yellow':'blue'}">${x.days<0?`${Math.abs(x.days)} T. abgelaufen`:`${x.days} T.`}</span></div>`}).join('')}</div>`:'<div class="empty">Keine Fristen in den nächsten 60 Tagen.</div>'}
  function renderRequirements(){const rows=requirements.filter(r=>r.active);$('#requirements-list').innerHTML=rows.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Pflicht</th><th>Typ</th><th>Geltung</th><th>Warnung</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td><b>${esc(r.label)}</b><div class="tiny muted">${esc(r.requirement_key)}</div></td><td>${esc(r.requirement_type)}</td><td>${r.site_id?esc(sites.find(s=>s.id===r.site_id)?.name||'Objekt'):'Unternehmensweit'}</td><td>${r.warning_days} Tage</td><td><button class="btn small red" data-disable-req="${r.id}">Deaktivieren</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Noch keine zusätzlichen Anforderungen definiert.</div>';document.querySelectorAll('[data-disable-req]').forEach(b=>b.onclick=()=>disableRequirement(b.dataset.disableReq))}
  async function disableRequirement(id){try{await AONE.update('guard_compliance_requirements',`id=eq.${encodeURIComponent(id)}`,{active:false});AONE.toast('Anforderung deaktiviert.');await load()}catch(e){AONE.toast(e.message,'err')}}
  function openQualification(){modal(`<div class="row between"><h2>Qualifikation hinzufügen</h2><button class="btn small" id="mclose">Schließen</button></div><div class="grid cols-2"><div class="field"><label>Mitarbeiter</label><select class="select" id="q-emp">${employees.filter(e=>e.status==='active').map(e=>`<option value="${e.id}">${esc(e.display_name)}</option>`).join('')}</select></div><div class="field"><label>Qualifikation</label><select class="select" id="q-kind">${common.map(([k,l])=>`<option value="${k}">${l}</option>`).join('')}<option value="sonstige">Sonstige</option></select></div><div class="field"><label>Aussteller</label><input class="input" id="q-issuer"></div><div class="field"><label>Referenznummer</label><input class="input" id="q-ref"></div><div class="field"><label>Gültig ab</label><input class="input" type="date" id="q-from"></div><div class="field"><label>Gültig bis</label><input class="input" type="date" id="q-until"></div></div><button class="btn primary block" id="q-save">Speichern & verifizieren</button>`);$('#mclose').onclick=close;$('#q-save').onclick=saveQualification}
  async function saveQualification(){const row={org_id:ctx.org_id,employee_id:$('#q-emp').value,kind:$('#q-kind').value,issuer:$('#q-issuer').value.trim()||null,reference_no:$('#q-ref').value.trim()||null,valid_from:$('#q-from').value||null,valid_until:$('#q-until').value||null,verified_at:new Date().toISOString(),verified_by:session.user.id};try{await AONE.insert('guard_qualifications',row);close();AONE.toast('Qualifikation gespeichert.');await load()}catch(e){AONE.toast(e.message,'err')}}
  function openRequirement(){modal(`<div class="row between"><h2>Anforderung definieren</h2><button class="btn small" id="mclose">Schließen</button></div><div class="field"><label>Bezeichnung</label><input class="input" id="r-label" placeholder="z. B. Erste Hilfe"></div><div class="grid cols-2"><div class="field"><label>Typ</label><select class="select" id="r-type"><option value="qualification">Qualifikation</option><option value="document">Dokument</option><option value="training">Unterweisung / Training</option></select></div><div class="field"><label>Schlüssel</label><input class="input" id="r-key" placeholder="erste_hilfe"></div><div class="field"><label>Geltung</label><select class="select" id="r-site"><option value="">Unternehmensweit</option>${sites.filter(s=>s.active).map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></div><div class="field"><label>Warnung vor Ablauf</label><input class="input" id="r-days" type="number" min="0" max="365" value="30"></div></div><button class="btn primary block" id="r-save">Anforderung speichern</button>`);$('#mclose').onclick=close;$('#r-save').onclick=saveRequirement}
  async function saveRequirement(){const key=$('#r-key').value.trim().toLowerCase().replace(/[^a-z0-9_-]+/g,'_');if(!key||!$('#r-label').value.trim())return AONE.toast('Bezeichnung und Schlüssel fehlen.','err');try{await AONE.insert('guard_compliance_requirements',{org_id:ctx.org_id,site_id:$('#r-site').value||null,requirement_type:$('#r-type').value,requirement_key:key,label:$('#r-label').value.trim(),warning_days:Number($('#r-days').value)||30,mandatory:true,created_by:session.user.id});close();AONE.toast('Anforderung gespeichert.');await load()}catch(e){AONE.toast(e.message,'err')}}
  $('#new-qualification').onclick=openQualification;$('#new-requirement').onclick=openRequirement;$('#search').oninput=renderMatrix;$('#risk-filter').onchange=renderMatrix;$('#site-filter').onchange=renderMatrix;$('#refresh').onclick=load;$('#logout').onclick=()=>{AONE.signOut();location.replace('./admin-login.html')};load();
})();