(()=>{
  const S={session:null,data:null,tab:'overview',customer:null};
  const $=s=>document.querySelector(s),esc=AONE.esc;
  const fmtHours=v=>`${Number(v||0).toLocaleString('de-DE',{minimumFractionDigits:2,maximumFractionDigits:2})} Std.`;
  const statusLabel=v=>({planned:'Geplant',confirmed:'Bestätigt',in_progress:'Läuft',completed:'Abgeschlossen',submitted:'Eingereicht',reviewed:'Geprüft',closed:'Geschlossen',issued:'Gestellt',paid:'Bezahlt',overdue:'Überfällig',open:'Offen',resolved:'Erledigt',canceled:'Storniert'})[v]||v||'—';
  const priorityPill=v=>v==='high'||v==='critical'?'red':v==='medium'?'yellow':'green';
  const iso=d=>d.toISOString().slice(0,10);
  async function init(){
    S.session=await AONE.session().catch(()=>null);if(!S.session){location.replace('./kunden-login.html');return}
    const from=new Date();from.setDate(from.getDate()-30);const to=new Date();to.setDate(to.getDate()+30);$('#date-from').value=iso(from);$('#date-to').value=iso(to);
    S.customer=localStorage.getItem('aone_customer_portal_customer')||null;
    $('#logout').onclick=()=>{AONE.signOut();localStorage.removeItem('aone_customer_portal_customer');location.replace('./kunden-login.html')};
    $('#refresh').onclick=refresh;$('#account-switch').onchange=()=>{S.customer=$('#account-switch').value||null;localStorage.setItem('aone_customer_portal_customer',S.customer||'');refresh()};
    document.querySelectorAll('#portal-tabs button').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));await refresh();
  }
  async function refresh(){
    AONE.loading(true,'Kundenportal laden…');
    try{
      const d=await AONE.rpc('guard_customer_portal_snapshot',{p_customer:S.customer||null,p_from:$('#date-from').value,p_to:$('#date-to').value});S.data=d;S.customer=d.account.customer_id;localStorage.setItem('aone_customer_portal_customer',S.customer);
      $('#company-name').textContent=d.account.company_name||'Kundenportal';$('#portal-subtitle').textContent=`${d.account.org_name||'A ONE Guard'} · ${d.account.customer_no||''}`;$('#portal-user').textContent=d.account.display_name||S.session.user.email||'Kunde';
      const sw=$('#account-switch'),accounts=d.accounts||[];sw.hidden=accounts.length<=1;sw.innerHTML=accounts.map(a=>`<option value="${a.customer_id}" ${a.customer_id===S.customer?'selected':''}>${esc(a.company_name)} · ${esc(a.org_name)}</option>`).join('');renderStats();render();
    }catch(e){if(/customer portal access not found|authentication required/i.test(e.message)){AONE.signOut();location.replace('./kunden-login.html');return}AONE.toast(e.message,'err');$('#portal-view').innerHTML=`<div class="card error">${esc(e.message)}</div>`}finally{AONE.loading(false)}
  }
  function setTab(tab){S.tab=tab;document.querySelectorAll('#portal-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));render()}
  function renderStats(){const k=S.data.kpis||{};$('#portal-stats').innerHTML=`<div class="card portal-kpi"><div class="muted">Objekte</div><div class="stat">${k.sites??0}</div><small class="muted">zugeordnet</small></div><div class="card portal-kpi"><div class="muted">Schichten im Zeitraum</div><div class="stat">${k.scheduled_shifts??0}</div><small class="muted">geplant</small></div><div class="card portal-kpi"><div class="muted">Rundgänge</div><div class="stat">${k.completed_patrols??0}</div><small class="muted">abgeschlossen</small></div><div class="card portal-kpi"><div class="muted">Offene Tickets</div><div class="stat">${k.open_tickets??0}</div><small class="muted">Reklamationen</small></div>`}
  function render(){if(!S.data)return;({overview:renderOverview,schedule:renderSchedule,hours:renderHours,watchbook:renderWatchbook,patrols:renderPatrols,incidents:renderIncidents,invoices:renderInvoices,tickets:renderTickets}[S.tab]||renderOverview)()}
  function renderOverview(){const d=S.data;$('#portal-view').innerHTML=`<div class="grid cols-2"><section class="card"><span class="kicker">Ihre Objekte</span><h2>Standorte</h2><div class="portal-card-list">${(d.sites||[]).map(x=>`<div class="portal-row"><h3>${esc(x.name)}</h3><div class="meta"><span>${esc(x.address||'Keine Adresse hinterlegt')}</span></div></div>`).join('')||'<div class="empty">Noch keine Objekte zugeordnet.</div>'}</div></section><section class="card"><span class="kicker">Aktuell</span><h2>Nächste Dienste</h2><div class="portal-card-list">${(d.shifts||[]).filter(x=>new Date(x.ends_at)>=new Date()).slice(0,6).map(shiftRow).join('')||'<div class="empty">Keine kommenden Dienste im Zeitraum.</div>'}</div></section></div><div class="grid cols-2" style="margin-top:14px"><section class="card"><h2>Letzte freigegebene Ereignisse</h2>${(d.watchbook||[]).slice(0,5).map(watchRow).join('')||'<div class="empty">Keine freigegebenen Wachbucheinträge.</div>'}</section><section class="card"><h2>Rechnungen</h2>${(d.invoices||[]).slice(0,5).map(invoiceRow).join('')||'<div class="empty">Keine Rechnungen verfügbar.</div>'}</section></div>`}
  function shiftRow(x){return `<div class="portal-row"><div class="row between wrap"><h3>${esc(x.site_name)}</h3><span class="pill">${esc(statusLabel(x.status))}</span></div><div class="meta"><span>${AONE.dt(x.starts_at)} – ${AONE.t(x.ends_at)}</span><span>${esc(x.employee_name||'Noch nicht besetzt')}</span></div></div>`}
  function renderSchedule(){$('#portal-view').innerHTML=`<section class="card"><div class="row between wrap"><div><span class="kicker">Dienstplan</span><h2>Besetzung Ihrer Objekte</h2></div><span class="pill">${(S.data.shifts||[]).length} Dienste</span></div><div class="portal-card-list">${(S.data.shifts||[]).map(shiftRow).join('')||'<div class="empty">Keine Dienste im gewählten Zeitraum.</div>'}</div></section>`}
  function renderHours(){const rows=S.data.hours||[],total=rows.reduce((a,x)=>a+Number(x.hours||0),0);$('#portal-view').innerHTML=`<section class="card"><div class="row between wrap"><div><span class="kicker">Proof of Service</span><h2>Geleistete Stunden</h2></div><div class="stat">${fmtHours(total)}</div></div><div class="table-wrap"><table class="table"><thead><tr><th>Datum</th><th>Objekt</th><th>Buchungen</th><th>Netto-Stunden</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(new Date(x.work_date+'T12:00:00').toLocaleDateString('de-DE'))}</td><td>${esc(x.site_name)}</td><td>${x.entries}</td><td><b>${fmtHours(x.hours)}</b></td></tr>`).join('')||'<tr><td colspan="4" class="empty">Keine abgeschlossenen Zeitbuchungen.</td></tr>'}</tbody></table></div></section>`}
  function watchRow(x){return `<div class="portal-row"><div class="row between wrap"><h3>${esc(x.site_name)}</h3><span class="pill ${priorityPill(x.severity)}">${esc(x.severity)}</span></div><div class="meta"><span>${AONE.dt(x.occurred_at)}</span><span>${esc(x.category)}</span></div><p>${esc(x.body)}</p></div>`}
  function renderWatchbook(){$('#portal-view').innerHTML=`<section class="card"><span class="kicker">Freigegeben</span><h2>Wachbuch</h2><p class="muted">Nur ausdrücklich freigegebene Einträge werden angezeigt.</p><div class="portal-card-list">${(S.data.watchbook||[]).map(watchRow).join('')||'<div class="empty">Keine freigegebenen Wachbucheinträge.</div>'}</div></section>`}
  function patrolRow(x){const done=Number(x.scans||0),all=Number(x.checkpoints||0),pct=all?Math.round(done/all*100):0;return `<div class="portal-row"><div class="row between wrap"><h3>${esc(x.route_name)} · ${esc(x.site_name)}</h3><span class="pill ${x.status==='completed'?'green':'yellow'}">${esc(statusLabel(x.status))}</span></div><div class="meta"><span>${AONE.dt(x.started_at)}</span><span>${done}/${all} Kontrollpunkte</span><span>${pct}%</span></div><div class="progress" style="margin-top:8px"><i style="width:${Math.min(100,pct)}%"></i></div></div>`}
  function renderPatrols(){$('#portal-view').innerHTML=`<section class="card"><span class="kicker">WKS Nachweise</span><h2>Freigegebene Rundgänge</h2><div class="portal-card-list">${(S.data.patrols||[]).map(patrolRow).join('')||'<div class="empty">Keine freigegebenen Rundgänge.</div>'}</div></section>`}
  function incidentRow(x){return `<div class="portal-row"><div class="row between wrap"><h3>${esc(x.title)}</h3><span class="pill ${priorityPill(x.severity)}">${esc(x.severity)}</span></div><div class="meta"><span>${esc(x.site_name)}</span><span>${AONE.dt(x.occurred_at)}</span><span>${esc(statusLabel(x.status))}</span></div><p>${esc(x.description)}</p>${x.immediate_actions?`<p><b>Maßnahmen:</b> ${esc(x.immediate_actions)}</p>`:''}${x.police_reference?`<div class="muted">Polizeivorgang: ${esc(x.police_reference)}</div>`:''}</div>`}
  function renderIncidents(){$('#portal-view').innerHTML=`<section class="card"><span class="kicker">Incident Reports</span><h2>Freigegebene Vorfälle</h2><div class="portal-card-list">${(S.data.incidents||[]).map(incidentRow).join('')||'<div class="empty">Keine freigegebenen Vorfälle.</div>'}</div></section>`}
  function invoiceRow(x){return `<div class="portal-row"><div class="row between wrap"><h3>${esc(x.invoice_no)}</h3><span class="pill ${x.status==='paid'?'green':x.status==='overdue'?'red':'blue'}">${esc(statusLabel(x.status))}</span></div><div class="meta"><span>${x.period_start?esc(new Date(x.period_start+'T12:00:00').toLocaleDateString('de-DE')):'—'} – ${x.period_end?esc(new Date(x.period_end+'T12:00:00').toLocaleDateString('de-DE')):'—'}</span><span>Fällig: ${x.due_on?esc(new Date(x.due_on+'T12:00:00').toLocaleDateString('de-DE')):'—'}</span></div><div style="margin-top:8px;font-size:22px;font-weight:900">${AONE.money(x.gross_cents)}</div></div>`}
  function renderInvoices(){$('#portal-view').innerHTML=`<section class="card"><span class="kicker">Faktura</span><h2>Rechnungen</h2><div class="portal-card-list">${(S.data.invoices||[]).map(invoiceRow).join('')||'<div class="empty">Keine gestellten Rechnungen vorhanden.</div>'}</div></section>`}
  function ticketRow(x){return `<div class="portal-row"><div class="row between wrap"><h3>${esc(x.subject)}</h3><span class="pill ${x.status==='resolved'||x.status==='closed'?'green':x.priority==='high'?'red':'yellow'}">${esc(statusLabel(x.status))}</span></div><div class="meta"><span>${AONE.dt(x.created_at)}</span><span>Priorität ${esc(x.priority)}</span></div><p>${esc(x.body)}</p>${x.resolution_note?`<div class="notice"><b>Antwort:</b> ${esc(x.resolution_note)}</div>`:''}</div>`}
  function renderTickets(){$('#portal-view').innerHTML=`<div class="ticket-grid"><section class="card"><span class="kicker">Neue Anfrage</span><h2>Reklamation / Ticket</h2><form id="ticket-form"><div class="field"><label>Objekt</label><select class="select" name="site_id"><option value="">Allgemein</option>${(S.data.sites||[]).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></div><div class="field"><label>Betreff</label><input class="input" name="subject" maxlength="180" required></div><div class="field"><label>Priorität</label><select class="select" name="priority"><option value="low">Niedrig</option><option value="medium" selected>Normal</option><option value="high">Hoch</option></select></div><div class="field"><label>Beschreibung</label><textarea class="textarea" name="body" maxlength="5000" required></textarea></div><button class="btn primary block">Ticket senden</button></form></section><section class="card"><span class="kicker">Verlauf</span><h2>Ihre Tickets</h2><div class="portal-card-list">${(S.data.tickets||[]).map(ticketRow).join('')||'<div class="empty">Noch keine Tickets.</div>'}</div></section></div>`;$('#ticket-form').onsubmit=submitTicket}
  async function submitTicket(e){e.preventDefault();const f=new FormData(e.currentTarget);try{AONE.loading(true,'Ticket senden…');await AONE.rpc('guard_customer_create_ticket',{p_customer:S.customer,p_site:f.get('site_id')||null,p_subject:String(f.get('subject')||'').trim(),p_body:String(f.get('body')||'').trim(),p_priority:f.get('priority')});AONE.toast('Ticket wurde übermittelt.');await refresh();setTab('tickets')}catch(err){AONE.toast(err.message,'err')}finally{AONE.loading(false)}}
  init();
})();