(()=>{
const $=s=>document.querySelector(s),esc=v=>AONE.esc(v??'');
const state={session:null,ctx:null,courses:[],employees:[],attempts:[],progress:[]};
function emp(id){return state.employees.find(x=>x.id===id)}function course(id){return state.courses.find(x=>x.id===id)}
function completedAttempts(){return state.attempts.filter(a=>a.completed_at)}
function renderMetrics(){const done=completedAttempts(),passed=done.filter(a=>a.passed===true).length;$('#m-employees').textContent=state.employees.length;$('#m-attempts').textContent=done.length;$('#m-pass').textContent=done.length?Math.round(passed/done.length*100)+'%':'0%';$('#m-lessons').textContent=state.progress.length}
function renderCourses(){const root=$('#course-report');if(!state.courses.length){root.innerHTML='<div class="empty">Keine Kurse vorhanden.</div>';return}root.innerHTML=state.courses.map(c=>{const at=completedAttempts().filter(a=>a.course_id===c.id),passedIds=new Set(at.filter(a=>a.passed).map(a=>a.employee_id)),avg=at.length?Math.round(at.reduce((n,a)=>n+Number(a.score_percent||0),0)/at.length):0,rate=state.employees.length?Math.round(passedIds.size/state.employees.length*100):0;return `<div class="course-report-row"><div class="top"><div><b>${esc(c.title)}</b><div class="muted" style="font-size:12px">${esc(c.mode==='exam'?'Prüfung':c.mode==='instruction'?'Unterweisung':'Lernkurs')}</div></div><span class="pill ${rate>=80?'green':rate>=50?'yellow':''}">${rate}% erreicht</span></div><div class="mini-stats"><span>${passedIds.size}/${state.employees.length} Mitarbeiter bestanden</span><span>${at.length} Versuche</span><span>Ø ${avg}%</span><span>${Number(c.points||0)} XP</span></div><div class="progressbar"><i style="width:${rate}%"></i></div></div>`}).join('')}
function employeeStats(e){const at=completedAttempts().filter(a=>a.employee_id===e.id),passed=at.filter(a=>a.passed).length,xp=at.reduce((n,a)=>n+Number(a.xp_earned||0),0),lessons=state.progress.filter(p=>p.employee_id===e.id).length;return {passed,xp,lessons}}
function renderEmployees(){const term=$('#employee-search').value.trim().toLowerCase(),rows=state.employees.filter(e=>!term||`${e.display_name} ${e.employee_no||''} ${e.email||''}`.toLowerCase().includes(term));$('#employee-report').innerHTML=rows.length?rows.map(e=>{const s=employeeStats(e);return `<div class="employee-row"><div><b>${esc(e.display_name)}</b><div class="muted" style="font-size:11px">${esc(e.employee_no||e.email||'')}</div></div><div><b>${s.passed}</b><div class="muted" style="font-size:11px">bestanden</div></div><div><b>${s.xp}</b><div class="muted" style="font-size:11px">XP</div></div><div><b>${s.lessons}</b><div class="muted" style="font-size:11px">Module</div></div></div>`}).join(''):'<div class="empty">Keine Mitarbeiter gefunden.</div>'}
function renderAttempts(){const rows=completedAttempts().slice(0,50);$('#attempt-body').innerHTML=rows.length?rows.map(a=>`<tr><td>${esc(emp(a.employee_id)?.display_name||'—')}</td><td>${esc(course(a.course_id)?.title||'—')}</td><td><b>${Number(a.score_percent||0).toFixed(0)}%</b></td><td><span class="pill ${a.passed?'green':'red'}">${a.passed?'Bestanden':'Nicht bestanden'}</span></td><td>${Number(a.xp_earned||0)} XP</td><td>${AONE.dt(a.completed_at)}</td></tr>`).join(''):'<tr><td colspan="6" class="empty">Noch keine Ergebnisse vorhanden.</td></tr>'}
function render(){renderMetrics();renderCourses();renderEmployees();renderAttempts()}
async function load(){AONE.loading(true,'Lernwelt-Auswertung wird geladen…');try{state.session=await AONE.session();if(!state.session){location.replace('./admin-login.html');return}state.ctx=await AONE.chooseContext();if(!state.ctx||!AONE.isManager(state.ctx.role)){location.replace('./admin-login.html');return}const [courses,employees,attempts,progress]=await Promise.all([AONE.table('guard_courses','select=id,title,category,mode,points,pass_percent,published&published=eq.true&order=title.asc'),AONE.table('guard_employees',`select=id,display_name,employee_no,email,status&org_id=eq.${encodeURIComponent(state.ctx.org_id)}&status=eq.active&order=display_name.asc`),AONE.table('guard_training_attempts',`select=id,employee_id,course_id,started_at,completed_at,score_percent,passed,xp_earned&org_id=eq.${encodeURIComponent(state.ctx.org_id)}&order=started_at.desc&limit=500`),AONE.table('guard_lesson_progress',`select=employee_id,lesson_id,completed_at&org_id=eq.${encodeURIComponent(state.ctx.org_id)}&order=completed_at.desc`)]);state.courses=courses||[];state.employees=employees||[];state.attempts=attempts||[];state.progress=progress||[];$('#org-name').textContent=state.ctx.org?.name||'Management';$('#who').textContent=AONE.roleLabel(state.ctx.role);render()}catch(e){AONE.toast(e.message||'Auswertung konnte nicht geladen werden.','err')}finally{AONE.loading(false)}}
$('#employee-search').addEventListener('input',renderEmployees);$('#refresh').onclick=load;$('#logout').onclick=()=>{AONE.signOut();location.replace('./admin-login.html')};load();
})();
