(()=>{
const $=s=>document.querySelector(s), state={ctx:null,user:null,employees:[],memberships:[],quals:[],current:null,privateRow:null};
const esc=v=>AONE.esc(v??'');
function msg(el,text,kind='ok'){el.innerHTML=text?`<div class="notice ${kind==='err'?'warn':''}" style="margin-top:10px">${esc(text)}</div>`:''}
function open(id){$(id).classList.add('open')} function close(id){$(id).classList.remove('open')}
function roleFor(e){return state.memberships.find(m=>m.user_id===e.user_id)?.role||'employee'}
function qualLabel(q){return ({none:'Keine',unterrichtung:'Unterrichtung',sachkunde:'Sachkunde'})[q]||q}
function roleLabel(r){return ({employee:'Mitarbeiter',dispatcher:'Schichtleitung',admin:'Admin',owner:'Inhaber'})[r]||r}
async function load(){AONE.loading(true,'Mitarbeiter werden geladen…');try{
 const org=state.ctx.org_id;
 const [employees,memberships,quals]=await Promise.all([
  AONE.table('guard_employees',`select=*&org_id=eq.${encodeURIComponent(org)}&order=display_name.asc`),
  AONE.table('guard_memberships',`select=org_id,user_id,role,active&org_id=eq.${encodeURIComponent(org)}`),
  AONE.table('guard_qualifications',`select=*&org_id=eq.${encodeURIComponent(org)}&order=created_at.desc`)
 ]);
 state.employees=employees||[];state.memberships=memberships||[];state.quals=quals||[];render();
}finally{AONE.loading(false)}}
function filtered(){const q=$('#search').value.toLowerCase().trim(),s=$('#status-filter').value,k=$('#qual-filter').value;return state.employees.filter(e=>(!q||[e.display_name,e.employee_no,e.email,e.phone].some(x=>String(x||'').toLowerCase().includes(q)))&&(!s||e.status===s)&&(!k||e.qualification_level===k))}
function render(){
 $('#m-active').textContent=state.employees.filter(e=>e.status==='active').length;$('#m-inactive').textContent=state.employees.filter(e=>e.status==='inactive').length;$('#m-sachkunde').textContent=state.employees.filter(e=>e.qualification_level==='sachkunde').length;$('#m-no-login').textContent=state.employees.filter(e=>!e.user_id).length;
 const list=filtered();$('#people-grid').innerHTML=list.length?list.map(e=>`<article class="person" data-id="${e.id}"><h3><span class="status-dot ${e.status==='active'?'active':''}"></span>${esc(e.display_name)}</h3><div class="sub">${esc(e.employee_no||'ohne Personalnummer')} · ${esc(e.email||'kein Login')}</div><div class="person-meta"><span>${esc(qualLabel(e.qualification_level))}</span><span>${esc(roleLabel(roleFor(e)))}</span><span>${esc(e.status)}</span>${e.bewacher_id?`<span>Bewacher-ID ${esc(e.bewacher_id)}</span>`:''}</div><div class="sub">${e.hourly_rate_cents!=null?AONE.money(e.hourly_rate_cents):'Stundenlohn nicht hinterlegt'} · ${e.vacation_days_annual??'—'} Urlaubstage</div></article>`).join(''):'<div class="empty-card">Keine Mitarbeiter gefunden.</div>';
}
async function openEmployee(id){const e=state.employees.find(x=>x.id===id);if(!e)return;state.current=e;$('#employee-id').value=e.id;$('#employee-user-id').value=e.user_id||'';$('#edit-title').textContent=e.display_name;$('#f-name').value=e.display_name||'';$('#f-no').value=e.employee_no||'';$('#f-email').value=e.email||'';$('#f-phone').value=e.phone||'';$('#f-bewacher').value=e.bewacher_id||'';$('#f-qual').value=e.qualification_level||'none';$('#f-status').value=e.status||'active';$('#f-role').value=roleFor(e);$('#f-role').disabled=!e.user_id;$('#f-rate').value=e.hourly_rate_cents==null?'':(e.hourly_rate_cents/100).toFixed(2);$('#f-vacation').value=e.vacation_days_annual??'';msg($('#form-msg'),'');
 renderQualifications(e.id);$('#private-help').textContent='';['p-birth','p-start','p-street','p-house','p-postal','p-city','p-emergency','p-emergency-phone'].forEach(x=>$('#'+x).value='');state.privateRow=null;
 try{const rows=await AONE.table('guard_employee_private',`select=*&employee_id=eq.${encodeURIComponent(e.id)}&org_id=eq.${encodeURIComponent(state.ctx.org_id)}&limit=1`);const p=rows?.[0];state.privateRow=p||null;if(p){$('#p-birth').value=p.birth_date||'';$('#p-start').value=p.employment_start_date||'';$('#p-street').value=p.street||'';$('#p-house').value=p.house_no||'';$('#p-postal').value=p.postal_code||'';$('#p-city').value=p.city||'';$('#p-emergency').value=p.emergency_contact||'';$('#p-emergency-phone').value=p.emergency_phone||''}}catch{$('#private-help').textContent='Private Personaldaten sind für deine Rolle nicht freigegeben.'}
 open('#edit-back');
}
function renderQualifications(empId){const rows=state.quals.filter(q=>q.employee_id===empId);$('#qualification-list').innerHTML=rows.length?rows.map(q=>`<div class="qual-row"><div><b>${esc(q.kind)}</b><div class="helper">${esc(q.issuer||'')}</div></div><div>${q.valid_until?`bis ${esc(q.valid_until)}`:'ohne Ablauf'}</div><div>${esc(q.reference_no||'—')}</div><button class="btn small remove-qual" data-id="${q.id}">Entfernen</button></div>`).join(''):'<div class="helper">Noch keine zusätzlichen Qualifikationen.</div>'}
async function saveEmployee(ev){ev.preventDefault();const e=state.current;if(!e)return;const data={display_name:$('#f-name').value.trim(),employee_no:$('#f-no').value.trim()||null,email:$('#f-email').value.trim().toLowerCase()||null,phone:$('#f-phone').value.trim()||null,bewacher_id:$('#f-bewacher').value.trim()||null,qualification_level:$('#f-qual').value,status:$('#f-status').value,hourly_rate_cents:$('#f-rate').value===''?null:Math.round(Number($('#f-rate').value)*100),vacation_days_annual:$('#f-vacation').value===''?null:Number($('#f-vacation').value)};AONE.loading(true,'Speichern…');try{await AONE.update('guard_employees',`id=eq.${encodeURIComponent(e.id)}&org_id=eq.${encodeURIComponent(state.ctx.org_id)}`,data);if(e.user_id&&$('#f-role').value!==roleFor(e))await AONE.rpc('guard_set_member_role',{p_org:state.ctx.org_id,p_user:e.user_id,p_role:$('#f-role').value});await load();state.current=state.employees.find(x=>x.id===e.id);$('#edit-title').textContent=state.current?.display_name||data.display_name;msg($('#form-msg'),'Gespeichert.')}catch(err){msg($('#form-msg'),err.message,'err')}finally{AONE.loading(false)}}
async function toggleActive(){const e=state.current;if(!e)return;const next=e.status==='active'?'inactive':'active';AONE.loading(true,'Status wird geändert…');try{await AONE.update('guard_employees',`id=eq.${encodeURIComponent(e.id)}&org_id=eq.${encodeURIComponent(state.ctx.org_id)}`,{status:next});if(e.user_id)await AONE.rpc('guard_set_member_active',{p_org:state.ctx.org_id,p_user:e.user_id,p_active:next==='active'}).catch(()=>{});await load();close('#edit-back');AONE.toast(next==='active'?'Mitarbeiter aktiviert.':'Mitarbeiter deaktiviert.')}catch(err){AONE.toast(err.message,'err')}finally{AONE.loading(false)}}
async function savePrivate(){const e=state.current;if(!e)return;const row={employee_id:e.id,org_id:state.ctx.org_id,birth_date:$('#p-birth').value||null,employment_start_date:$('#p-start').value||null,street:$('#p-street').value.trim()||null,house_no:$('#p-house').value.trim()||null,postal_code:$('#p-postal').value.trim()||null,city:$('#p-city').value.trim()||null,emergency_contact:$('#p-emergency').value.trim()||null,emergency_phone:$('#p-emergency-phone').value.trim()||null,updated_by:state.user.id};AONE.loading(true,'Personaldaten speichern…');try{if(state.privateRow)await AONE.update('guard_employee_private',`employee_id=eq.${encodeURIComponent(e.id)}`,row);else await AONE.insert('guard_employee_private',row,false);state.privateRow=row;AONE.toast('Private Personaldaten gespeichert.')}catch(err){AONE.toast(err.message,'err')}finally{AONE.loading(false)}}
async function addQual(){const e=state.current,kind=$('#q-kind').value.trim();if(!e||!kind)return AONE.toast('Bitte Art der Qualifikation eintragen.','warn');AONE.loading(true,'Qualifikation speichern…');try{await AONE.insert('guard_qualifications',{org_id:state.ctx.org_id,employee_id:e.id,kind,issuer:$('#q-issuer').value.trim()||null,reference_no:$('#q-ref').value.trim()||null,valid_until:$('#q-until').value||null},false);$('#q-kind').value='';$('#q-issuer').value='';$('#q-ref').value='';$('#q-until').value='';await load();renderQualifications(e.id);AONE.toast('Qualifikation hinzugefügt.')}catch(err){AONE.toast(err.message,'err')}finally{AONE.loading(false)}}
async function removeQual(id){if(!confirm('Qualifikation entfernen?'))return;try{await AONE.remove('guard_qualifications',`id=eq.${encodeURIComponent(id)}&org_id=eq.${encodeURIComponent(state.ctx.org_id)}`);state.quals=state.quals.filter(x=>x.id!==id);renderQualifications(state.current.id)}catch(err){AONE.toast(err.message,'err')}}
async function createEmployee(ev){ev.preventDefault();msg($('#new-msg'),'');$('#credentials').innerHTML='';const display_name=$('#n-name').value.trim(),email=$('#n-email').value.trim().toLowerCase(),employee_no=$('#n-no').value.trim()||null,qualification_level=$('#n-qual').value,role=$('#n-role').value,access=$('#n-access').value;if(display_name.length<2)return msg($('#new-msg'),'Name fehlt.','err');if(access==='login'&&!email)return msg($('#new-msg'),'Für einen Login-Zugang ist eine E-Mail-Adresse erforderlich.','err');AONE.loading(true,'Mitarbeiter wird angelegt…');try{if(access==='login'){const r=await AONE.edge('guard-admin-create-user',{org_id:state.ctx.org_id,email,display_name,employee_no,qualification_level,role});$('#credentials').innerHTML=`<div class="cred"><b>Zugang erstellt</b><p>${esc(r.email)}</p><div class="helper">Temporäres Passwort – jetzt kopieren, es wird danach nicht erneut angezeigt:</div><code>${esc(r.temporary_password)}</code></div>`}else{await AONE.insert('guard_employees',{org_id:state.ctx.org_id,display_name,email:email||null,employee_no,qualification_level,status:'active'},false);msg($('#new-msg'),'Personalakte wurde ohne Login angelegt.')}await load();$('#new-form').reset();$('#n-access').value='login'}catch(err){msg($('#new-msg'),err.message,'err')}finally{AONE.loading(false)}}
function bind(){['search','status-filter','qual-filter'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',render));$('#people-grid').onclick=e=>{const card=e.target.closest('.person');if(card)openEmployee(card.dataset.id)};$('#new-employee').onclick=()=>{msg($('#new-msg'),'');$('#credentials').innerHTML='';open('#new-back')};$('#close-new').onclick=()=>close('#new-back');$('#close-edit').onclick=()=>close('#edit-back');$('#employee-form').onsubmit=saveEmployee;$('#toggle-active').onclick=toggleActive;$('#save-private').onclick=savePrivate;$('#add-qualification').onclick=addQual;$('#qualification-list').onclick=e=>{if(e.target.classList.contains('remove-qual'))removeQual(e.target.dataset.id)};$('#new-form').onsubmit=createEmployee;$('#refresh').onclick=load;$('#logout').onclick=()=>{AONE.signOut();location.replace('./admin-login.html')};document.querySelectorAll('.panel-back').forEach(x=>x.addEventListener('click',e=>{if(e.target===x)x.classList.remove('open')}))}
async function init(){const s=await AONE.session();if(!s){location.replace('./admin-login.html');return}state.user=s.user;const ctx=await AONE.chooseContext();if(!ctx||!AONE.isManager(ctx.role)){location.replace('./admin-login.html');return}state.ctx=ctx;$('#org-name').textContent=ctx.org?.name||'Mitarbeiter';$('#who').textContent=AONE.roleLabel(ctx.role);bind();await load()}
init().catch(e=>AONE.toast(e.message,'err'));
})();
