(()=>{
const $=s=>document.querySelector(s),state={ctx:null,sites:[],current:null};const esc=v=>AONE.esc(v??'');
function msg(el,text,kind='ok'){el.innerHTML=text?`<div class="notice ${kind==='err'?'warn':''}" style="margin-top:10px">${esc(text)}</div>`:''}function open(){ $('#site-back').classList.add('open')}function close(){ $('#site-back').classList.remove('open')}
function policyLabel(v){return ({off:'Standort aus',record:'Standort protokollieren',enforce:'Geofence erzwingen'})[v]||v}
function updateHelp(){const p=$('#f-policy').value;$('#policy-help').textContent=p==='off'?'Standortdaten werden für die Zeiterfassung nicht geprüft.':p==='record'?'Standort wird beim Stempeln – falls verfügbar – protokolliert, blockiert die Buchung aber nicht.':'Einstempeln/Ausstempeln wird nur innerhalb des konfigurierten Geofence zugelassen. Dafür müssen Koordinaten gesetzt sein.'}
async function load(){AONE.loading(true,'Objekte werden geladen…');try{state.sites=await AONE.table('guard_sites',`select=*&org_id=eq.${encodeURIComponent(state.ctx.org_id)}&order=name.asc`)||[];render()}finally{AONE.loading(false)}}
function filtered(){const q=$('#search').value.toLowerCase().trim(),p=$('#policy-filter').value,a=$('#active-filter').value;return state.sites.filter(s=>(!q||[s.name,s.customer_name,s.address].some(x=>String(x||'').toLowerCase().includes(q)))&&(!p||s.location_policy===p)&&(a===''||String(s.active)===a))}
function render(){const active=state.sites.filter(s=>s.active);$('#m-active').textContent=active.length;$('#m-enforce').textContent=active.filter(s=>s.location_policy==='enforce').length;$('#m-coords').textContent=active.filter(s=>s.latitude!=null&&s.longitude!=null).length;$('#m-inactive').textContent=state.sites.filter(s=>!s.active).length;const list=filtered();$('#site-grid').innerHTML=list.length?list.map(s=>`<article class="site-card" data-id="${s.id}"><h3>${esc(s.name)}</h3><div class="sub">${esc(s.customer_name||'kein Kunde')} · ${esc(s.address||'keine Adresse')}</div><div class="meta"><span>${esc(policyLabel(s.location_policy))}</span><span>${s.geofence_radius_m} m</span><span>${s.active?'Aktiv':'Inaktiv'}</span>${s.latitude!=null&&s.longitude!=null?'<span>Standort gesetzt</span>':'<span>Standort fehlt</span>'}</div></article>`).join(''):'<div class="empty-card">Keine Objekte gefunden.</div>'}
function edit(id){const s=state.sites.find(x=>x.id===id);if(!s)return;state.current=s;$('#site-id').value=s.id;$('#site-title').textContent=s.name;$('#f-name').value=s.name||'';$('#f-customer').value=s.customer_name||'';$('#f-address').value=s.address||'';$('#f-lat').value=s.latitude??'';$('#f-lng').value=s.longitude??'';$('#f-radius').value=s.geofence_radius_m||150;$('#f-policy').value=s.location_policy||'record';$('#f-active').value=String(!!s.active);updateHelp();msg($('#site-msg'),'');open()}
function fresh(){state.current=null;$('#site-form').reset();$('#site-id').value='';$('#site-title').textContent='Neues Objekt';$('#f-radius').value=150;$('#f-policy').value='record';$('#f-active').value='true';updateHelp();msg($('#site-msg'),'');open()}
async function save(ev){ev.preventDefault();const name=$('#f-name').value.trim();if(name.length<2)return msg($('#site-msg'),'Objektname fehlt.','err');const row={name,customer_name:$('#f-customer').value.trim()||null,address:$('#f-address').value.trim()||null,latitude:$('#f-lat').value===''?null:Number($('#f-lat').value),longitude:$('#f-lng').value===''?null:Number($('#f-lng').value),geofence_radius_m:Number($('#f-radius').value||150),location_policy:$('#f-policy').value,active:$('#f-active').value==='true'};if(row.location_policy==='enforce'&&(row.latitude==null||row.longitude==null))return msg($('#site-msg'),'Für „Geofence erzwingen“ müssen Koordinaten gesetzt sein.','err');AONE.loading(true,'Objekt speichern…');try{if(state.current)await AONE.update('guard_sites',`id=eq.${encodeURIComponent(state.current.id)}&org_id=eq.${encodeURIComponent(state.ctx.org_id)}`,row);else await AONE.insert('guard_sites',{org_id:state.ctx.org_id,...row},false);await load();close();AONE.toast('Objekt gespeichert.')}catch(err){msg($('#site-msg'),err.message,'err')}finally{AONE.loading(false)}}
async function useLocation(){AONE.loading(true,'Standort wird ermittelt…');try{const g=await AONE.geolocate();$('#f-lat').value=g.lat.toFixed(7);$('#f-lng').value=g.lng.toFixed(7);AONE.toast(`Standort übernommen (Genauigkeit ca. ${g.accuracy} m).`)}catch(err){AONE.toast(err.message,'err')}finally{AONE.loading(false)}}
function bind(){['search','policy-filter','active-filter'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',render));$('#site-grid').onclick=e=>{const c=e.target.closest('.site-card');if(c)edit(c.dataset.id)};$('#new-site').onclick=fresh;$('#close-site').onclick=close;$('#site-form').onsubmit=save;$('#use-location').onclick=useLocation;$('#f-policy').onchange=updateHelp;$('#refresh').onclick=load;$('#logout').onclick=()=>{AONE.signOut();location.replace('./admin-login.html')};$('#site-back').addEventListener('click',e=>{if(e.target===$('#site-back'))close()})}
async function init(){const s=await AONE.session();if(!s){location.replace('./admin-login.html');return}const ctx=await AONE.chooseContext();if(!ctx||!AONE.isManager(ctx.role)){location.replace('./admin-login.html');return}state.ctx=ctx;$('#org-name').textContent=ctx.org?.name||'Objekte';$('#who').textContent=AONE.roleLabel(ctx.role);bind();await load()}init().catch(e=>AONE.toast(e.message,'err'));
})();
