(()=>{
  const $=s=>document.querySelector(s);let session,ctx,employees=[],current=null,privateRow=null,quals=[],docs=[],leaves=[];const esc=AONE.esc;
  async function guard(){session=await AONE.session().catch(()=>null);if(!session){location.replace('./admin-login.html');return false}ctx=await AONE.chooseContext();if(!ctx||!['owner','admin'].includes(ctx.role)){location.replace('./admin.html');return false}$('#org-name').textContent=ctx.org.name;$('#who').textContent=AONE.roleLabel(ctx.role);return true}
  async function init(){AONE.loading(true,'Personalakte laden…');try{if(!await guard())return;employees=await AONE.table('guard_employees',`select=*&org_id=eq.${encodeURIComponent(ctx.org_id)}&order=display_name.asc`);const id=new URLSearchParams(location.search).get('id');$('#employee-select').innerHTML=employees.map(e=>`<option value="${e.id}">${esc(e.display_name)}${e.employee_no?` · ${esc(e.employee_no)}`:''}</option>`).join('');if(id&&employees.some(e=>e.id===id))$('#employee-select').value=id;$('#employee-select').onchange=loadEmployee;await loadEmployee()}catch(e){AONE.toast(e.message,'err')}finally{AONE.loading(false)}}
  async function loadEmployee(){const id=$('#employee-select').value;if(!id)return;current=employees.find(e=>e.id===id);AONE.loading(true,'Akte laden…');try{const org=encodeURIComponent(ctx.org_id),emp=encodeURIComponent(id);const [pr,q,d,l]=await Promise.all([AONE.table('guard_employee_private',`select=*&org_id=eq.${org}&employee_id=eq.${emp}&limit=1`),AONE.table('guard_qualifications',`select=*&org_id=eq.${org}&employee_id=eq.${emp}&order=created_at.desc`),AONE.table('guard_document_register',`select=*&org_id=eq.${org}&employee_id=eq.${emp}&order=created_at.desc`),AONE.table('guard_leave_requests',`select=*&org_id=eq.${org}&employee_id=eq.${emp}&order=created_at.desc`)]);privateRow=pr[0]||null;quals=q;docs=d;leaves=l;render()}catch(e){AONE.toast(e.message,'err')}finally{AONE.loading(false)}}
  function render(){renderMaster();renderPrivate();renderQuals();renderDocs();renderLeave()}
  function renderMaster(){$('#master').innerHTML=`<div class="record-grid"><div><div class="kicker">Name</div><h2>${esc(current.display_name)}</h2></div><div><div class="kicker">Personalnummer</div><div class="stat" style="font-size:22px">${esc(current.employee_no||'—')}</div></div><div><div class="kicker">Status</div><span class="pill ${current.status==='active'?'green':'red'}">${esc(current.status)}</span></div><div><b>E-Mail</b><div class="muted">${esc(current.email||'—')}</div></div><div><b>Telefon</b><div class="muted">${esc(current.phone||'—')}</div></div><div><b>Bewacher-ID</b><div class="muted">${esc(current.bewacher_id||'—')}</div></div><div><b>Basisqualifikation</b><div class="muted">${esc(current.qualification_level||'none')}</div></div><div><b>Urlaub / Jahr</b><div class="muted">${current.vacation_days_annual??'—'}</div></div><div><b>Stundenlohn</b><div class="muted">${current.hourly_rate_cents!=null?AONE.money(current.hourly_rate_cents):'—'}</div></div></div>`}
  function f(id,label,type='text',value=''){return `<div class="field"><label for="${id}">${label}</label><input class="input" id="${id}" type="${type}" value="${esc(value||'')}"></div>`}
  function renderPrivate(){const p=privateRow||{};$('#private').innerHTML=`<div class="subtle-lock">Vertrauliche HR-Daten · nicht für Dispatcher oder Mitarbeiter sichtbar</div><div class="record-grid" style="margin-top:12px">${f('p-birth','Geburtsdatum','date',p.birth_date)}${f('p-nationality','Staatsangehörigkeit','text',p.nationality)}${f('p-taxclass','Steuerklasse','text',p.tax_class)}${f('p-street','Straße','text',p.street)}${f('p-house','Hausnr.','text',p.house_no)}${f('p-postal','PLZ','text',p.postal_code)}${f('p-city','Ort','text',p.city)}${f('p-country','Land','text',p.country||'Deutschland')}${f('p-taxid','Steuer-ID','text',p.tax_id)}${f('p-social','Sozialversicherungsnr.','text',p.social_security_no)}${f('p-health','Krankenkasse','text',p.health_insurance)}${f('p-iban','IBAN','text',p.iban)}${f('p-bic','BIC','text',p.bic)}${f('p-start','Beschäftigt seit','date',p.employment_start_date)}${f('p-end','Beschäftigt bis','date',p.employment_end_date)}${f('p-emergency','Notfallkontakt','text',p.emergency_contact)}${f('p-emergency-phone','Notfalltelefon','text',p.emergency_phone)}</div><button class="btn primary" id="save-private" style="margin-top:16px">Vertrauliche Daten speichern</button>`;$('#save-private').onclick=savePrivate}
  async function savePrivate(){const row={employee_id:current.id,org_id:ctx.org_id,birth_date:$('#p-birth').value||null,nationality:$('#p-nationality').value.trim()||null,tax_class:$('#p-taxclass').value.trim()||null,street:$('#p-street').value.trim()||null,house_no:$('#p-house').value.trim()||null,postal_code:$('#p-postal').value.trim()||null,city:$('#p-city').value.trim()||null,country:$('#p-country').value.trim()||'Deutschland',tax_id:$('#p-taxid').value.trim()||null,social_security_no:$('#p-social').value.trim()||null,health_insurance:$('#p-health').value.trim()||null,iban:$('#p-iban').value.trim()||null,bic:$('#p-bic').value.trim()||null,employment_start_date:$('#p-start').value||null,employment_end_date:$('#p-end').value||null,emergency_contact:$('#p-emergency').value.trim()||null,emergency_phone:$('#p-emergency-phone').value.trim()||null,updated_at:new Date().toISOString(),updated_by:session.user.id};try{if(privateRow)await AONE.update('guard_employee_private',`employee_id=eq.${encodeURIComponent(current.id)}&org_id=eq.${encodeURIComponent(ctx.org_id)}`,row);else await AONE.insert('guard_employee_private',row);AONE.toast('Personalakte gespeichert.');await loadEmployee()}catch(e){AONE.toast(e.message,'err')}}
  function qs(q){const d=q.valid_until?new Date(q.valid_until+'T00:00:00'):null;const now=new Date();now.setHours(0,0,0,0);if(d&&d<now)return ['Abgelaufen','red'];if(d&&((d-now)/86400000)<=30)return ['Läuft bald ab','yellow'];if(!q.verified_at)return ['Ungeprüft','yellow'];return ['Gültig','green']}
  function renderQuals(){$('#quals').innerHTML=quals.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Qualifikation</th><th>Aussteller</th><th>Gültig</th><th>Status</th></tr></thead><tbody>${quals.map(q=>{const s=qs(q);return `<tr><td><b>${esc(q.kind)}</b><div class="tiny muted">${esc(q.reference_no||'')}</div></td><td>${esc(q.issuer||'—')}</td><td>${q.valid_from?AONE.d(q.valid_from):'—'} – ${q.valid_until?AONE.d(q.valid_until):'unbefristet'}</td><td><span class="pill ${s[1]}">${s[0]}</span></td></tr>`}).join('')}</tbody></table></div><div style="margin-top:12px"><a class="btn" href="./compliance.html">Im Compliance Center bearbeiten</a></div>`:'<div class="empty">Noch keine Qualifikationen hinterlegt.<br><a class="btn" href="./compliance.html" style="display:inline-block;margin-top:12px">Qualifikation hinzufügen</a></div>'}
  function docStatus(d){if(d.status==='obsolete')return ['Ersetzt','red'];if(d.status==='draft'||d.status==='in_review')return ['In Prüfung','yellow'];if(d.valid_until){const x=new Date(d.valid_until+'T23:59:59'),now=new Date(),days=(x-now)/86400000;if(days<0)return ['Abgelaufen','red'];if(days<=30)return ['Läuft bald ab','yellow']}return [d.status==='sent'?'Gesendet':d.status==='archived'?'Archiviert':'Freigegeben','green']}
  function renderDocs(){
    const active=docs.filter(d=>d.status!=='obsolete'),expired=active.filter(d=>d.valid_until&&new Date(d.valid_until+'T23:59:59')<new Date()).length,due=active.filter(d=>d.valid_until&&new Date(d.valid_until+'T23:59:59')>=new Date()&&(new Date(d.valid_until+'T23:59:59')-new Date())/86400000<=30).length;
    const head=`<div class="row between wrap" style="margin-bottom:12px"><div><b>${active.length} aktive Dokumente</b><div class="tiny muted">${expired} abgelaufen · ${due} laufen in 30 Tagen ab</div></div><div class="row wrap"><a class="btn small primary" href="./documents.html?employee=${encodeURIComponent(current.id)}&new=1">+ Dokument hochladen</a><a class="btn small" href="./documents.html?employee=${encodeURIComponent(current.id)}">Dokumentenzentrale</a></div></div>`;
    if(!docs.length){$('#docs').innerHTML=head+'<div class="empty">Keine Dokumente in der Personalakte.</div>';return}
    $('#docs').innerHTML=head+`<div class="table-wrap"><table class="table"><thead><tr><th>Dokument</th><th>Nr.</th><th>Status</th><th>Gültig bis</th><th></th></tr></thead><tbody>${docs.map(d=>{const s=docStatus(d);return `<tr><td><b>${esc(d.title)}</b><div class="tiny muted">${esc(d.category)}${d.metadata?.compliance_key?` · ${esc(d.metadata.compliance_key)}`:''}</div></td><td>${esc(d.document_no||'—')} · v${d.version_no||1}</td><td><span class="pill ${s[1]}">${s[0]}</span></td><td>${d.valid_until?AONE.d(d.valid_until):'—'}</td><td><button class="btn small" data-open-doc="${d.id}">Öffnen</button></td></tr>`}).join('')}</tbody></table></div>`;
    document.querySelectorAll('[data-open-doc]').forEach(b=>b.onclick=()=>openDoc(b.dataset.openDoc))
  }
  async function openDoc(id){const d=docs.find(x=>x.id===id);if(!d)return;AONE.loading(true,'Dokument öffnen…');try{await AONE.rpc('guard_log_document_access',{p_document:id,p_access_type:'open'});await AONE.openStorage('guard-documents',d.storage_path,d.original_filename||d.title)}catch(e){AONE.toast(e.message,'err')}finally{AONE.loading(false)}}
  function renderLeave(){$('#leave').innerHTML=leaves.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Art</th><th>Zeitraum</th><th>Status</th><th>Notiz</th></tr></thead><tbody>${leaves.map(l=>`<tr><td>${l.kind==='vacation'?'Urlaub':l.kind==='sick'?'Krank':'Sonstiges'}</td><td>${AONE.d(l.starts_on)} – ${AONE.d(l.ends_on)}</td><td><span class="pill ${l.status==='approved'?'green':l.status==='rejected'?'red':l.status==='pending'?'yellow':''}">${esc(l.status)}</span></td><td>${esc(l.note||'—')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Keine Abwesenheiten.</div>'}
  document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.section-pane').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});init();
})();
