(()=>{const $=s=>document.querySelector(s),esc=AONE.esc;let session,ctx,archives=[],current=null;
function fmtMonth(v){if(!v)return'—';const d=new Date(String(v).slice(0,10)+'T12:00:00');return new Intl.DateTimeFormat('de-DE',{month:'long',year:'numeric'}).format(d)}
function csv(rows,cols){const q=v=>`"${String(v??'').replace(/"/g,'""')}"`;return [cols.map(c=>q(c[0])).join(';'),...rows.map(r=>cols.map(c=>q(typeof c[1]==='function'?c[1](r):r[c[1]])).join(';'))].join('\n')}
function save(name,data,type='text/plain;charset=utf-8'){const b=new Blob([data],{type}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000)}
async function guard(){session=await AONE.session();if(!session){location.replace('./admin-login.html');return false}ctx=await AONE.chooseContext();if(!ctx||!AONE.isManager(ctx.role)){location.replace('./admin.html');return false}$('#org-name').textContent=ctx.org?.name||'Reporting';$('#who').textContent=AONE.roleLabel(ctx.role);return true}
async function load(){AONE.loading(true,'Archive laden…');try{if(!await guard())return;archives=await AONE.table('guard_monthly_archives',`select=*&org_id=eq.${encodeURIComponent(ctx.org_id)}&order=period_start.desc`)||[];render()}catch(e){AONE.toast(e.message,'err')}finally{AONE.loading(false)}}
function render(){const latest=archives[0],s=latest?.snapshot?.summary||{};$('#stats').innerHTML=`<div class="metric"><b>${archives.length}</b><span>versiegelte Monate</span></div><div class="metric"><b>${latest?fmtMonth(latest.period_start):'—'}</b><span>letztes Archiv</span></div><div class="metric"><b>${latest?Math.round(Number(s.worked_minutes||0)/60):0} h</b><span>Arbeitszeit im letzten Archiv</span></div><div class="metric"><b>${latest?Number(s.incidents||0)+Number(s.watchbook_entries||0):0}</b><span>Ereignisse im letzten Archiv</span></div>`;renderList();if(current){const fresh=archives.find(x=>x.id===current.id);if(fresh){current=fresh;renderDetail()}}}
function renderList(){const term=$('#search').value.toLowerCase().trim();const list=archives.filter(a=>!term||fmtMonth(a.period_start).toLowerCase().includes(term)||String(a.period_start).includes(term));$('#archives').innerHTML=list.length?list.map(a=>{const s=a.snapshot?.summary||{};return `<article class="archive-card" data-id="${a.id}"><div class="row between"><span class="pill blue">VERSIEGELT</span><span class="tiny muted">Schema v${a.snapshot?.schema_version||'?'}</span></div><h3>${esc(fmtMonth(a.period_start))}</h3><div class="archive-meta"><span>${Number(s.employee_count||0)} Mitarbeiter · ${Number(s.shift_count||0)} Schichten</span><span>${(Number(s.worked_minutes||0)/60).toFixed(1)} Std. · ${Number(s.patrol_runs||0)} Rundgänge</span><span>${Number(s.watchbook_entries||0)} Wachbuch · ${Number(s.incidents||0)} Incidents</span><span>Erstellt ${AONE.dt(a.generated_at)}</span></div><button class="btn small open-archive" data-id="${a.id}">Öffnen</button></article>`}).join(''):'<div class="empty" style="grid-column:1/-1">Noch kein Monatsarchiv vorhanden.</div>'}
function renderDetail(){if(!current)return;const s=current.snapshot?.summary||{},snap=current.snapshot||{};$('#detail-panel').hidden=false;$('#detail-title').textContent=fmtMonth(current.period_start);$('#integrity').textContent=`SHA-256: ${current.checksum_sha256||current.snapshot_hash||'—'}`;$('#integrity').className='muted';$('#detail-summary').innerHTML=[['Mitarbeiter',s.employee_count],['Schichten',s.shift_count],['Arbeitszeit',`${(Number(s.worked_minutes||0)/60).toFixed(1)} h`],['Wachbuch',s.watchbook_entries],['Rundgänge',s.patrol_runs],['Incidents',s.incidents],['Fahrten',s.vehicle_trips],['Dokumente',s.documents]].map(([k,v])=>`<div class="summary-item"><b>${esc(v??0)}</b><span class="muted">${esc(k)}</span></div>`).join('');$('#detail-more').innerHTML=`<div class="row wrap"><span class="pill">${(snap.time_entries||[]).length} Zeitbuchungen</span><span class="pill">${(snap.qualifications||[]).length} Qualifikationen</span><span class="pill">${(snap.training_attempts||[]).length} Prüfungsversuche</span><span class="pill">${(snap.leave_requests||[]).length} Abwesenheiten</span><span class="pill">${(snap.shift_swaps||[]).length} Tauschvorgänge</span></div>`;$('#print-sheet').innerHTML=`<h1>A ONE Guard · Monatsarchiv ${esc(fmtMonth(current.period_start))}</h1><p><b>${esc(ctx.org?.name||'')}</b><br>Zeitraum ${esc(current.period_start)} bis ${esc(current.period_end)}<br>Versiegelt: ${esc(AONE.dt(current.generated_at))}</p><table><tr><th>Mitarbeiter</th><th>Schichten</th><th>Arbeitsstunden</th><th>Wachbuch</th><th>WKS</th><th>Incidents</th><th>Fahrten</th></tr><tr><td>${s.employee_count||0}</td><td>${s.shift_count||0}</td><td>${(Number(s.worked_minutes||0)/60).toFixed(2)}</td><td>${s.watchbook_entries||0}</td><td>${s.patrol_runs||0}</td><td>${s.incidents||0}</td><td>${s.vehicle_trips||0}</td></tr></table><p><small>SHA-256: ${esc(current.checksum_sha256||'')}</small></p>`;$('#detail-panel').scrollIntoView({behavior:'smooth',block:'start'})}
async function createArchive(){const v=$('#month').value;if(!v)return AONE.toast('Bitte einen Monat auswählen.','err');const first=v+'-01',d=new Date(first+'T12:00:00'),now=new Date();if(d.getFullYear()>now.getFullYear()||(d.getFullYear()===now.getFullYear()&&d.getMonth()>=now.getMonth()))return AONE.toast('Nur abgeschlossene Monate können archiviert werden.','err');AONE.loading(true,'Monat wird versiegelt…');try{await AONE.rpc('guard_create_monthly_archive',{p_org:ctx.org_id,p_month:first});await load();AONE.toast('Monatsarchiv erstellt.')}catch(e){AONE.toast(e.message,'err')}finally{AONE.loading(false)}}
async function verify(){if(!current)return;AONE.loading(true,'Integrität prüfen…');try{const ok=await AONE.rpc('guard_verify_monthly_archive',{p_archive:current.id});$('#integrity').textContent=(ok?'Integrität bestätigt · ':'Integritätsfehler · ')+(current.checksum_sha256||'');$('#integrity').className=ok?'integrity-ok':'integrity-bad';AONE.toast(ok?'Archiv unverändert.':'Archivprüfung fehlgeschlagen.',ok?'ok':'err')}catch(e){AONE.toast(e.message,'err')}finally{AONE.loading(false)}}
async function loggedExport(format,note,fn){try{await AONE.rpc('guard_log_export',{p_org:ctx.org_id,p_entity_type:'monthly_archive',p_entity_id:current?.id||null,p_format:format,p_note:note})}catch{}fn()}
function jsonExport(){if(!current)return;loggedExport('json','Monatsarchiv JSON',()=>save(`AONE-${current.period_start}-archiv.json`,JSON.stringify(current.snapshot,null,2),'application/json'))}
function timeExport(){const rows=current?.snapshot?.time_entries||[];loggedExport('csv','Arbeitszeitreport',()=>save(`AONE-${current.period_start}-arbeitszeit.csv`,csv(rows,[['Mitarbeiter-ID','employee_id'],['Objekt-ID','site_id'],['Start','clock_in_at'],['Ende','clock_out_at'],['Pause Min.','break_minutes'],['Status','status']]),'text/csv;charset=utf-8'))}
function watchbookExport(){const rows=current?.snapshot?.watchbook||[];loggedExport('csv','Wachbuchreport',()=>save(`AONE-${current.period_start}-wachbuch.csv`,csv(rows,[['Zeit','occurred_at'],['Objekt-ID','site_id'],['Mitarbeiter-ID','employee_id'],['Kategorie','category'],['Priorität','severity'],['Eintrag','body']]),'text/csv;charset=utf-8'))}
function wksExport(){const rows=current?.snapshot?.patrol_runs||[];loggedExport('csv','WKS Report',()=>save(`AONE-${current.period_start}-wks.csv`,csv(rows,[['Start','started_at'],['Ende','completed_at'],['Mitarbeiter-ID','employee_id'],['Route-ID','route_id'],['Status','status'],['Scans',r=>(r.scans||[]).length]]),'text/csv;charset=utf-8'))}
function incidentExport(){const rows=current?.snapshot?.incident_reports||[];loggedExport('csv','Incident Report',()=>save(`AONE-${current.period_start}-incidents.csv`,csv(rows,[['Nr.','incident_no'],['Zeit','occurred_at'],['Objekt-ID','site_id'],['Kategorie','category'],['Priorität','severity'],['Titel','title'],['Status','status']]),'text/csv;charset=utf-8'))}
$('#archives').onclick=e=>{const b=e.target.closest('.open-archive');if(!b)return;current=archives.find(x=>x.id===b.dataset.id);renderDetail()};$('#create-archive').onclick=createArchive;$('#verify').onclick=verify;$('#download-json').onclick=jsonExport;$('#download-time').onclick=timeExport;$('#download-watchbook').onclick=watchbookExport;$('#download-wks').onclick=wksExport;$('#download-incidents').onclick=incidentExport;$('#print').onclick=()=>current&&loggedExport('print','Monatsarchiv Druck',()=>AONE.printNode($('#print-sheet'),`A ONE Guard ${fmtMonth(current.period_start)}`));$('#search').oninput=renderList;$('#refresh').onclick=load;$('#logout').onclick=()=>{AONE.signOut();location.replace('./admin-login.html')};const pm=new Date();pm.setMonth(pm.getMonth()-1);$('#month').value=`${pm.getFullYear()}-${String(pm.getMonth()+1).padStart(2,'0')}`;load();})();