/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type GuardIncidentSeverity = "critical" | "high" | "info" | "low" | "medium";

export type GuardOrgRole = "admin" | "dispatcher" | "employee" | "owner";

export type GuardShiftStatus = "active" | "canceled" | "completed" | "confirmed" | "planned";

export type GuardTimeAction = "break_end" | "break_start" | "clock_in" | "clock_out";

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "user";

export interface GuardAuditLog {
  action: string;
  actorUserId: Int8 | null;
  createdAt: Generated<Timestamp>;
  entityId: string | null;
  entityType: string;
  id: Generated<Int8>;
  metadata: Generated<Json>;
  orgId: string | null;
}

export interface GuardComplianceRecords {
  createdAt: Generated<Timestamp>;
  employeeId: string;
  id: Generated<string>;
  issuedAt: Timestamp | null;
  notes: string | null;
  orgId: string;
  recordType: string;
  referenceNo: string | null;
  validUntil: Timestamp | null;
}

export interface GuardEmployees {
  active: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  displayName: string;
  email: string | null;
  employeeNo: string | null;
  id: Generated<string>;
  orgId: string;
  phone: string | null;
  qualification: string | null;
  userId: Int8 | null;
}

export interface GuardImportBatches {
  createdAt: Generated<Timestamp>;
  createdBy: Int8 | null;
  errors: Generated<Json>;
  fileName: string;
  finishedAt: Timestamp | null;
  id: Generated<string>;
  importedRows: Generated<number>;
  importType: string;
  orgId: string;
  skippedRows: Generated<number>;
  status: Generated<string>;
  totalRows: Generated<number>;
}

export interface GuardIncidents {
  createdAt: Generated<Timestamp>;
  createdBy: Int8 | null;
  description: string;
  employeeId: string | null;
  id: Generated<string>;
  occurredAt: Generated<Timestamp>;
  orgId: string;
  severity: Generated<GuardIncidentSeverity>;
  shiftId: string | null;
  siteId: string | null;
  status: Generated<string>;
  title: string;
}

export interface GuardMemberships {
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  orgId: string;
  role: Generated<GuardOrgRole>;
  userId: Int8;
}

export interface GuardNfcTags {
  active: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  label: string;
  orgId: string;
  siteId: string;
  token: string;
}

export interface GuardOrganizations {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  planCode: Generated<string>;
  slug: string;
  subscriptionStatus: Generated<string>;
  trialEndsAt: Timestamp | null;
}

export interface GuardPatrolPoints {
  active: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  label: string;
  orgId: string;
  siteId: string;
  sortOrder: Generated<number>;
  token: string;
}

export interface GuardPatrolScans {
  accuracyM: number | null;
  createdBy: Int8 | null;
  employeeId: string;
  id: Generated<Int8>;
  latitude: Numeric | null;
  longitude: Numeric | null;
  occurredAt: Generated<Timestamp>;
  orgId: string;
  pointId: string;
  siteId: string;
}

export interface GuardShifts {
  createdAt: Generated<Timestamp>;
  createdBy: Int8 | null;
  employeeId: string | null;
  endsAt: Timestamp;
  id: Generated<string>;
  importKey: string | null;
  notes: string | null;
  orgId: string;
  requiredQualification: string | null;
  siteId: string;
  startsAt: Timestamp;
  status: Generated<GuardShiftStatus>;
  title: Generated<string>;
}

export interface GuardSites {
  active: Generated<boolean>;
  address: string | null;
  createdAt: Generated<Timestamp>;
  customerName: string | null;
  geofenceRadiusM: Generated<number>;
  id: Generated<string>;
  latitude: Numeric | null;
  longitude: Numeric | null;
  name: string;
  orgId: string;
}

export interface GuardTimeEntries {
  accuracyM: number | null;
  action: GuardTimeAction;
  createdBy: Int8 | null;
  employeeId: string;
  id: Generated<Int8>;
  latitude: Numeric | null;
  longitude: Numeric | null;
  nfcTagId: string | null;
  note: string | null;
  occurredAt: Generated<Timestamp>;
  orgId: string;
  shiftId: string | null;
  siteId: string | null;
  source: Generated<string>;
}

export interface LoginAttempts {
  attemptedAt: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  success: Generated<boolean | null>;
}

export interface Sessions {
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: string;
  lastAccessed: Generated<Timestamp | null>;
  userId: number;
}

export interface UserPasswords {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  passwordHash: string;
  userId: number;
}

export interface Users {
  avatarUrl: string | null;
  createdAt: Generated<Timestamp | null>;
  displayName: string;
  email: string;
  id: Generated<number>;
  role: Generated<UserRole>;
  updatedAt: Generated<Timestamp | null>;
}

export interface DB {
  guardAuditLog: GuardAuditLog;
  guardComplianceRecords: GuardComplianceRecords;
  guardEmployees: GuardEmployees;
  guardImportBatches: GuardImportBatches;
  guardIncidents: GuardIncidents;
  guardMemberships: GuardMemberships;
  guardNfcTags: GuardNfcTags;
  guardOrganizations: GuardOrganizations;
  guardPatrolPoints: GuardPatrolPoints;
  guardPatrolScans: GuardPatrolScans;
  guardShifts: GuardShifts;
  guardSites: GuardSites;
  guardTimeEntries: GuardTimeEntries;
  loginAttempts: LoginAttempts;
  sessions: Sessions;
  userPasswords: UserPasswords;
  users: Users;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const UserRoleArrayValues: [UserRole, ...UserRole[]] = ["admin","user"];
export const GuardOrgRoleArrayValues: [GuardOrgRole, ...GuardOrgRole[]] = ["admin","dispatcher","employee","owner"];
export const GuardShiftStatusArrayValues: [GuardShiftStatus, ...GuardShiftStatus[]] = ["active","canceled","completed","confirmed","planned"];
export const GuardTimeActionArrayValues: [GuardTimeAction, ...GuardTimeAction[]] = ["break_end","break_start","clock_in","clock_out"];
export const GuardIncidentSeverityArrayValues: [GuardIncidentSeverity, ...GuardIncidentSeverity[]] = ["critical","high","info","low","medium"];
// Table/column names whose snake_case spelling kysely's default CamelCasePlugin
// cannot recover from the camelCase name used in code (an underscore directly
// before a digit, e.g. reminder_48h_sent ⇄ reminder48hSent). The db helper's
// CamelCasePlugin subclass consults this map so those identifiers work in
// queries. Regenerated on every schema pull.
export const kyselyIdentifierOverrides: Record<string, string> = {};

// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.

